# Generated by Django 3.2.3 on 2022-01-13 13:10

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logbooks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('PSK31', 'PSK31'), ('DSTAR', 'DSTAR'), ('SSTV', 'SSTV'), ('RTTY', 'RTTY'), ('SSB', 'SSB'), ('USB', 'USB'), ('LSB', 'LSB'), ('FT8', 'FT8'), ('AM', 'AM'), ('FM', 'FM'), ('CW', 'CW')], max_length=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('frequency', models.FloatField(default=0.0)),
                ('time', models.TimeField(auto_now_add=True)),
                ('callsign', models.CharField(max_length=10)),
                ('band', models.FloatField()),
                ('report_received', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(599), django.core.validators.MinValueValidator(111)])),
                ('report_send', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(599), django.core.validators.MinValueValidator(111)])),
                ('comments', models.TextField(blank=True, null=True)),
                ('favorite', models.BooleanField(default=False)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logs.logbook')),
            ],
        ),
    ]
